name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - "27.1"
          - "28.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Emacs ${{ matrix.emacs-version }}
        uses: purcell/setup-emacs@92ece5b58c04d4c154ca49b58413b5373bfa83d8
        with:
          version: ${{ matrix.emacs-version }}
      - name: Test
        run: bin/test.sh
